import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import {
  Bookmark,
  FileText,
  Printer,
  Download,
  Share2,
  Trash2,
  Shield,
  BookOpen,
  Scale,
  FileCheck,
  Sparkles,
  AlertTriangle,
  CheckCircle2
} from 'lucide-react';
import { authoritativeSources } from '../../data/ipData';

export const ReportsView: React.FC = () => {
  const { savedAnswers, deleteSavedAnswer, showToast } = useApp();
  const [selectedReportId, setSelectedReportId] = useState<string>('rep-01');

  // Sample Comprehensive Dossier Report
  const sampleDossier = {
    id: 'rep-01',
    title: 'AshwaCurcumin Bio-Synergy IP & Regulatory Dossier',
    date: 'September 2026',
    status: 'Ready for Review',
    confidenceScore: 91,
    executiveSummary: 'Comprehensive IP and regulatory strategy evaluation for a nano-lipid formulation of Withania somnifera and Curcuma longa. While direct botanical combinations face strict Section 3(p) non-patentability bars, patent protection is viable for the nano-lipid extraction delivery system. Concurrently, trademark registration under Class 5, Rule 158B licensing as Proprietary ASU Medicine, and National Biodiversity Authority Form III clearance are required.',
    productProfile: {
      name: 'AshwaCurcumin Bio-Synergy',
      botanicals: 'Withania somnifera (400mg), Curcuma longa (250mg, 95% Curcuminoids), Piper nigrum (10mg)',
      deliveryForm: 'Self-Emulsifying Nano-Lipid Softgel',
      indications: 'Joint mobility, chronic osteoarthritis inflammation, neuro-cognitive recovery'
    },
    regimes: [
      { name: 'Patent', status: 'CONDITIONAL', desc: 'Focus claims exclusively on the nano-lipid carrier and synergistic bio-absorption ratios.' },
      { name: 'Traditional Knowledge', status: 'BARRED PRIOR ART', desc: 'CSIR-TKDL Records RG/2180 and AK/1429 document ancient usage in Rasayana and Vatarakta.' },
      { name: 'ABS (Biodiversity)', status: 'MANDATORY CLEARANCE', desc: 'Form III approval from NBA required prior to patent grant under Section 6 of Biological Diversity Act.' },
      { name: 'Drug Regulation', status: 'PROPRIETARY ASU', desc: 'Licensing under Rule 158B(IV) with 3-batch stability and published safety dossier to State Licensing Authority.' },
      { name: 'Trademark', status: 'RECOMMENDED', desc: 'Register coined, arbitrary brand name under Nice Classes 5 and 35.' }
    ],
    risks: [
      'Pre-grant opposition from CSIR-TKDL or competitors citing Section 3(p) and 3(e).',
      'Non-bailable penalties under Section 55 of Biological Diversity Act if commercial sale begins without SBB intimation.',
      'Rejection of brand name if deceptively similar to classical Sanskrit formulation names.'
    ],
    recommendations: [
      'Complete combination index (CI < 0.8) synergy studies in validated cell lines before filing patent claims.',
      'Submit Form III to National Biodiversity Authority simultaneously with IPO patent examination request.',
      'Establish strict internal non-disclosure agreements (NDAs) to protect exact homogenization RPM and lipid ratios as Trade Secrets.',
      'File for Rule 158B ASU manufacturing license with State AYUSH Licensing Authority.'
    ],
    sources: authoritativeSources.slice(0, 5)
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadDossier = () => {
    const reportText = `
IP-SAKTI SAHAYAK — AYURVEDIC IP & REGULATORY DOSSIER
==================================================
Title: ${sampleDossier.title}
Date: ${sampleDossier.date}
AI Confidence: ${sampleDossier.confidenceScore}% (High)

EXECUTIVE SUMMARY
-----------------
${sampleDossier.executiveSummary}

PRODUCT FORMULATION PROFILE
---------------------------
Product: ${sampleDossier.productProfile.name}
Active Botanicals: ${sampleDossier.productProfile.botanicals}
Dosage Form: ${sampleDossier.productProfile.deliveryForm}
Indications: ${sampleDossier.productProfile.indications}

IP REGIMES MATRIX
-----------------
${sampleDossier.regimes.map(r => `• ${r.name} [${r.status}]: ${r.desc}`).join('\n')}

STATUTORY RISKS
---------------
${sampleDossier.risks.map(rk => `• ${rk}`).join('\n')}

RECOMMENDED ROADMAP
-------------------
${sampleDossier.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

SOURCES CONSULTED
-----------------
${sampleDossier.sources.map(s => `• ${s.title} (${s.section}) - Authority: ${s.authority}`).join('\n')}

DISCLAIMER: Generated by IP-SAKTI Sahayak AI assistant for educational and research purposes. Does not constitute formal legal counsel.
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `IP_Dossier_${sampleDossier.title.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showToast('Dossier Downloaded', 'Exported text dossier successfully', 'success');
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-stone-200 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-emerald-800 bg-emerald-100 px-2.5 py-0.5 rounded-full border border-emerald-200">
              IP Dossier Generator
            </span>
            <span className="text-xs text-stone-500">SIH26045 Module 6</span>
          </div>
          <h1 className="text-2xl font-black text-stone-900 tracking-tight mt-1 flex items-center gap-2">
            <FileText className="w-6 h-6 text-emerald-800" />
            <span>Saved Reports & Ayurvedic IP Dossiers</span>
          </h1>
          <p className="text-xs sm:text-sm text-stone-600 mt-0.5">
            Structured, printable legal tech dossiers compiling multi-regime IP strategy, TKDL citations, and AYUSH regulatory compliance.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="px-3 py-1.5 rounded-xl border border-stone-200 bg-white hover:bg-stone-50 text-stone-700 font-semibold text-xs flex items-center gap-1.5 shadow-2xs transition-colors"
          >
            <Printer className="w-3.5 h-3.5 text-stone-500" />
            <span>Print Dossier</span>
          </button>
          <button
            onClick={handleDownloadDossier}
            className="px-4 py-1.5 rounded-xl bg-emerald-800 hover:bg-emerald-900 text-white font-bold text-xs flex items-center gap-1.5 shadow-xs transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-emerald-300" />
            <span>Export Text Dossier</span>
          </button>
        </div>
      </div>

      {/* Main Dossier Report Paper UI */}
      <div className="bg-white rounded-2xl border border-stone-200 p-6 sm:p-8 shadow-sm space-y-6">
        
        {/* Dossier Header */}
        <div className="border-b border-stone-200 pb-6 flex flex-col md:flex-row md:items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-[10px] font-mono font-bold text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                DOSSIER #IP-2026-ASU-042
              </span>
              <span className="text-xs text-stone-400 font-medium">• {sampleDossier.date}</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-black text-stone-900">
              {sampleDossier.title}
            </h2>
            <p className="text-xs text-stone-500 mt-0.5">
              Prepared for Ayurvedic Innovation & Regulatory Filing Team
            </p>
          </div>

          <div className="p-3 bg-stone-50 rounded-xl border border-stone-200 text-right">
            <div className="text-[10px] font-bold text-stone-400 uppercase tracking-wider">Overall Confidence</div>
            <div className="text-xl font-black text-emerald-800">{sampleDossier.confidenceScore}%</div>
            <div className="text-[10px] font-semibold text-emerald-700">Verified Evidence</div>
          </div>
        </div>

        {/* 1. Executive Summary */}
        <div className="space-y-1.5">
          <h3 className="text-xs font-bold text-stone-900 uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-emerald-700" />
            <span>1. Executive Legal & Regulatory Summary</span>
          </h3>
          <p className="text-xs text-stone-700 leading-relaxed bg-stone-50 p-4 rounded-xl border border-stone-200">
            {sampleDossier.executiveSummary}
          </p>
        </div>

        {/* 2. Product & Formulation Specification */}
        <div className="space-y-1.5">
          <h3 className="text-xs font-bold text-stone-900 uppercase tracking-wider flex items-center gap-1.5">
            <FileText className="w-3.5 h-3.5 text-stone-700" />
            <span>2. Formulation Specification Profile</span>
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs bg-white p-4 rounded-xl border border-stone-200">
            <div>
              <span className="font-bold text-stone-500">Product Name: </span>
              <span className="text-stone-900 font-semibold">{sampleDossier.productProfile.name}</span>
            </div>
            <div>
              <span className="font-bold text-stone-500">Delivery Form: </span>
              <span className="text-stone-900 font-semibold">{sampleDossier.productProfile.deliveryForm}</span>
            </div>
            <div className="sm:col-span-2">
              <span className="font-bold text-stone-500">Botanical Actives: </span>
              <span className="text-stone-900 font-semibold">{sampleDossier.productProfile.botanicals}</span>
            </div>
            <div className="sm:col-span-2">
              <span className="font-bold text-stone-500">Therapeutic Indications: </span>
              <span className="text-stone-900 font-semibold">{sampleDossier.productProfile.indications}</span>
            </div>
          </div>
        </div>

        {/* 3. Multi-Regime IP Analysis Matrix */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold text-stone-900 uppercase tracking-wider flex items-center gap-1.5">
            <Scale className="w-3.5 h-3.5 text-amber-700" />
            <span>3. Multi-Regime IP Strategy Analysis</span>
          </h3>
          <div className="space-y-2">
            {sampleDossier.regimes.map((reg, idx) => (
              <div key={idx} className="p-3 bg-stone-50 rounded-xl border border-stone-200 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                <div className="min-w-0 flex-1">
                  <span className="font-bold text-stone-900">{reg.name}: </span>
                  <span className="text-stone-600">{reg.desc}</span>
                </div>
                <span className="text-[10px] font-extrabold px-2.5 py-0.5 rounded-full bg-white border border-stone-200 text-stone-800 shrink-0 self-start sm:self-auto">
                  {reg.status}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* 4. Risks & Recommendations (2 Columns) */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 bg-rose-50/50 rounded-xl border border-rose-200 space-y-2 text-xs">
            <h4 className="font-bold text-rose-900 uppercase tracking-wider flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5 text-rose-600" />
              <span>4. Key Legal & Statutory Risks</span>
            </h4>
            <ul className="space-y-1.5 text-stone-700">
              {sampleDossier.risks.map((rk, i) => (
                <li key={i} className="flex items-start gap-1.5">
                  <span className="text-rose-600 font-bold">•</span>
                  <span>{rk}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="p-4 bg-emerald-50/50 rounded-xl border border-emerald-200 space-y-2 text-xs">
            <h4 className="font-bold text-emerald-900 uppercase tracking-wider flex items-center gap-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
              <span>5. Actionable Roadmap & Next Steps</span>
            </h4>
            <ul className="space-y-1.5 text-stone-700">
              {sampleDossier.recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-1.5">
                  <span className="text-emerald-700 font-bold">{i + 1}.</span>
                  <span>{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* 5. Statutory Sources Consulted */}
        <div className="space-y-2 pt-2 border-t border-stone-200">
          <h3 className="text-xs font-bold text-stone-900 uppercase tracking-wider flex items-center gap-1.5">
            <BookOpen className="w-3.5 h-3.5 text-emerald-700" />
            <span>6. Statutory References & Pharmacopoeial Authorities</span>
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 text-xs">
            {sampleDossier.sources.map(src => (
              <div key={src.id} className="p-2.5 bg-stone-50 rounded-lg border border-stone-200">
                <div className="font-bold text-stone-900 text-xs truncate">{src.title}</div>
                <div className="text-[10px] text-stone-500 font-mono">{src.section}</div>
                <div className="text-[10px] text-stone-400 mt-1 truncate">{src.authority}</div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
};
